# Site settings
theme: jekyll-uno
title: PRINCE ITIMO'S NOTE
description: 'I buy/sell all digital assets 
Gift-cards | $BTC(₿) | $ETH(Ξ) | $BNB(◈) | $USDT(₮) 
When I'm not busy trading or reading, I'm hitting the road for a drive.'
url: 'http://princeitimo.github.io'
baseurl: '/princeitimo.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'PRINCE ITIMO'
  email: 
  twitter_username: princeitimo
  facebook_username: 
  github_username:  
  instagram_username:  princeitimo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
